### ISSUE TITLE
Dataset Groups: Parameters in DB connection not supported

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/pentaho-pdi-dataset#10]
It seems like that if parameters are used in the DB connection (and the connection is working when tested via the DB connection dialog), the Dataset Group still does not support them:
![screen shot 2016-11-26 at 20 56 49](https://cloud.githubusercontent.com/assets/1726057/20643842/109a28b6-b41b-11e6-87b2-cdc4c9c234a9.png)
![screen shot 2016-11-26 at 20 57 21](https://cloud.githubusercontent.com/assets/1726057/20643843/16bb4db0-b41b-11e6-872a-3975386e02d2.png)

**Comment by mattcasters** [comment]
Better connection handling, variables and so on will be fixed in 2.1.0 after my vacation
