### ISSUE TITLE
Unit test passes if there is no data in the unit test input table

### ISSUE THREAD

**Issue by milesgawthorp** [mattcasters/pentaho-pdi-dataset#12]
To replicate:
Create a unit_test_input table in your database, but do not add any values.
Create a unit_test_output table in your database and populate with your golden data.
Associate these with the first and last steps of your transformation.
Enable the Unit Test and Run

Actual result:
The unit test runs successfully and logs 'Test passed succesfully against unit test'     -- successfully has 2 s.

Expected results:
The unit test to fail as no comparison is being made.

**Comment by cdeptula** [comment]
+1 If a step with a golden data set receives 0 rows, the unit test passes instead of failing with an incorrect number of rows error.  This could be for any reason including an upstream hop being disabled, or an upstream step being disabled.

**Comment by mattcasters** [comment]
Confirmed the issue

**Comment by mattcasters** [comment]
I added a warning message and made sure the situation fails now: "WARNING: no test results found for step 'Output' : check disabled hops, input and so on."
