### ISSUE TITLE
!ShowUnitTestMenuExtensionPoint.ErrorEditingUnitTest.Message! Needs tranlation

### ISSUE THREAD

**Issue by cdeptula** [mattcasters/pentaho-pdi-dataset#13]
When trying to edit a unit test that is not in your local metastore you get the token version of the error message.  These tokens need a translation in messages.en_us:

ShowUnitTestMenuExtensionPoint.ErrorEditingUnitTest.Message
ShowUnitTestMenuExtensionPoint.ErrorEditingUnitTest.Title

**Comment by mattcasters** [comment]
Should be fixed in 87d3cd4
