### ISSUE TITLE
Remove data set group does not work

### ISSUE THREAD

**Issue by cdeptula** [mattcasters/pentaho-pdi-dataset#14]
The Tools > Data set > Data set groups > Remove data set group menu item currently does not work.  When you click on it, nothing happens in Spoon.

In the console log you get the following error:

java.lang.NoSuchMethodException: org.pentaho.di.dataset.spoon.DataSetHelper.removeDataSetGroup()
at java.lange.Class.getMethod(Class.java:1786)
...

**Comment by mattcasters** [comment]
Latest commit implemented this. 76b6f88
