### ISSUE TITLE
Add ability to inject parameter values in unit test

### ISSUE THREAD

**Issue by cdeptula** [mattcasters/pentaho-pdi-dataset#15]
When you execute an individual unit test through Spoon it executes with the parameter values defined at run time.  When you execute a unit test using the Execute Unit Tests step it uses parameters defined in that transformation, and if a transformation being unit tested has a parameter that is not defined in the parent transformation it gets ${parameter_name}.

Often times the parameter value is critical to the output of a transformation, and there are cases where I want to have multiple unit tests for a transformation that all use different parameter values.  It would be good to have the option to save the parameter values in the unit test itself which would allow for multiple unit tests to use different parameter values.

**Comment by mattcasters** [comment]
Hi Chris, sorry it took so long to pick this comment up.  Do you think we could supply parameters values for testing in the definition dialog of the test, like we did for database mappings?
Without feedback from you that's where I would solve this issue.

**Comment by cdeptula** [comment]
I think configuring them in the test definition dialog makes sense and would work well.

**Comment by mattcasters** [comment]
Also planned for 2.1.0
