### ISSUE TITLE
Allow data sets to be deleted

### ISSUE THREAD

**Issue by mattcasters** [mattcasters/pentaho-pdi-dataset#18]
Implement a safe delete checking all unit tests to see if the test to be deleted is used as Input or Golden.

**Comment by mattcasters** [comment]
for 2.1.0

**Comment by Michele100** [comment]
Hi Matt,
can you please add CSV data sets to be deleted?
Thanks.

**Comment by mattcasters** [comment]
Absolutely on the roadmap.  For now just remove the definition file from the metastore folder.
```metastore/pentaho/Kettle Data Set``` (by default in ```$HOME/.pentaho```)

**Comment by Michele100** [comment]
Great - looking forward to it ;-)
