### ISSUE TITLE
Add data set group: Database pull down menu not populated

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/pentaho-pdi-dataset#2]
When creating a new data set group, the database pull down menu is not populated. I tried typing in the database name, however, the value still does not get accepted. Hence it is impossible to create a data set group. UPDATE: It seems like you have to first "share" the defined database connection before the dialog picks up the values.

**Comment by mattcasters** [comment]
It indeed only picks up shared databases.  I'll add a [new] button later which does that for ya.

**Comment by mattcasters** [comment]
Should be fixed in [commit](https://github.com/mattcasters/pentaho-pdi-dataset/commit/06e65c2a2d2345db5bfeb5a358e97c535d9315c8)
