### ISSUE TITLE
Allow selection of tests to be performed

### ISSUE THREAD

**Issue by harrisward** [mattcasters/pentaho-pdi-dataset#21]
The Execute Unit test step can filter tests by Type. Would it be useful to allow this step to accept a user defined list of unit tests to execute with also the possibility to access a field from a previous step with test xml filenames to run from the metastore directory.

developers could use the get Filename step in a job and pass a list down to the execute unit tests step to better manage blocks of tests being executed instead of ALL by Type

**Comment by harrisward** [comment]
Its possible to do this already if you manipulate the filesystm to move the unit test xml files in and out of the metastore directory which could be done using a job that loops over the execute unit tests step transformation but its still a nice to have in the step itself

**Comment by mattcasters** [comment]
in 3.1
