### ISSUE TITLE
Unit Test changes are not applied to the current transformation when Run

### ISSUE THREAD

**Issue by harrisward** [mattcasters/pentaho-pdi-dataset#22]
When you edit a unit test within a KTR and click Run the unit test XML is updated but the transformation that runs the unit test does not execute the latest update changes. You must save the transformation first before clicking Run. This is likely because the transformation itself has not been changes so does not detect and automatically save when Run is executed.

**Comment by mattcasters** [comment]
Also applied to clearing golden and input data sets, thanks Harris.  We need to save constantly anytime something changes to a unit test.
