### ISSUE TITLE
UI Bug - UI Elements disappear When Cancel is clicked on New Unit Test

### ISSUE THREAD

**Issue by harrisward** [mattcasters/pentaho-pdi-dataset#23]
Open a transformation with a unit test applied. You can see the UI elements for input data etc. Click New Unit Test and then Cancel on the popup dialog. The UI elements for the original unit test disappear although the unit test is still applied to the transformation.

Click Switch and reselecting the Unit Test will obviously bring back the UI elements even thought the unit test was actually still attached

**Comment by mattcasters** [comment]
Nice catch, thanks Harris!
