### ISSUE TITLE
UNIT_TESTS_BASE_PATH Parameter not correctly defined

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/pentaho-pdi-dataset#26]
The **Transformation unit test** dialog has the **Base test path** prepopulated with `UNIT_TESTS_BASE_PATH`. Please change to `${UNIT_TESTS_BASE_PATH}`. Thanks!

**Comment by mattcasters** [comment]
Or just empty since ```${UNIT_TESTS_BASE_PATH}``` is the default.

**Comment by diethardsteiner** [comment]
Ok, but still it should have the missing `${` and `}`. So instead of `UNIT_TESTS_BASE_PATH` use `${UNIT_TESTS_BASE_PATH}`.

**Comment by mattcasters** [comment]
No, it's better to remove it.  It's better to have the kettle-environment manage these system settings.
