### ISSUE TITLE
Test data from text files

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/pentaho-pdi-dataset#27]
As a developer I’d like to source my unit test data directly from CSV/text files. I tried to use H2 for this, however, it requires one connection by file which is inconvinient - there does not seem to be an option to configure a connection to point to a folder full of csv/text files (see also [here](
https://stackoverflow.com/questions/53302467/one-h2-connection-to-folder-with-csv-files)). For this reason, can you please implement an option to directly source unit test data from csv/text files?

**Comment by diethardsteiner** [comment]
Excellent, thanks a lot!
Just for everyone's info: The folder containing the CSV files can be specified on a **dataset group** level.

**Comment by mattcasters** [comment]
Actually, it can now be configured on the Environment level.  This makes it super easy to configure your projects.
