### ISSUE TITLE
Unit Tests: Support parameterised path

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/pentaho-pdi-dataset#33]
Currently it seems like the absolute path to the ktr gets saved in the unit test. As a developer I want to be flexible and have an option available to parameterise the path. E.g. Developer A stores his files in `/home/a/git/myproject/` whereas developer B stores her files in `/home/b/work/projects/myproject`: Both work on the same project, but on different files.

**Comment by mattcasters** [comment]
You need to set variable UNIT_TESTS_BASE_PATH for this.
The kettle-environment project handles this for you.

https://github.com/mattcasters/pentaho-pdi-dataset/wiki/Basic-documentation
