### ISSUE TITLE
Bug: Specifying parameter not support for Dataset Group CSV Folder Path

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/pentaho-pdi-dataset#34]
While `DATASETS_BASE_PATH` is picked up when running a unit test, if I were to define this parameter or any other for the CSV folder path within the Dataset Group dialog, this parameter is currently not picked up.

**Comment by mattcasters** [comment]
I actually ran into this one a while back and forgot to log this.

**Comment by diethardsteiner** [comment]
Thanks!
