### ISSUE TITLE
Data Sets and Parameterized Connections

### ISSUE THREAD

**Issue by OpenDataAlex** [mattcasters/pentaho-pdi-dataset#35]
I think I've found an issue with parameterized data connections.  I'm testing this with the environments plugin, unit testing plugin, and needful-things plugin.  When trying to Add Data Set and clicking on Get Metadata I receive an error:  Error connecting to database: (using class org.postgresql.Driver)
No suitable driver found for jdbc:postgresql://${host_name_par}:${port_par}/$database_name_par} .  I am able to connect to this normally through Table input steps and the like.

**Comment by OpenDataAlex** [comment]
Apologies - forgot what version of PDI: 8.2 CE

**Comment by mattcasters** [comment]
Should be fixed Alex, re-open if you still have an issue.
