### ISSUE TITLE
Data set for Table Input Step not working

### ISSUE THREAD

**Issue by Michele100** [mattcasters/pentaho-pdi-dataset#37]
Hi.
If there is a Table Input step and the connection to the database is not working (for example, the remote DB is not available), then it's not possible to associate a Unit Test to that step.
The Error message panel comes up complaining that the connection :
![image](https://user-images.githubusercontent.com/20770778/51187292-6d27c600-18d3-11e9-9f51-837a46287e96.png)

**Comment by diethardsteiner** [comment]
This is especially important in environments that are completely locked down and no proper dev environment is in place (e.g. no MySQL databaser access available at all).

**Comment by mattcasters** [comment]
I have to ask for a reproduction path. If the Table Input step does not have an input data set then this is normal.

**Comment by mattcasters** [comment]
OK, I prodded around a bit and it seems like this is an issue with Kettle itself which we'll need to circumvent somehow.  I'll fix this over the next couple of days.

**Comment by diethardsteiner** [comment]
Excellent, thanks a lot!

On 21 Jan 2019, at 10:17, Matt Casters <notifications@github.com> wrote:

OK, I prodded around a bit and it seems like this is an issue with Kettle itself which we'll need to circumvent somehow. I'll fix this over the next couple of days.

**Comment by mattcasters** [comment]
Should be fixed in 3.4.0, give it a try.
Thanks for the feedback!

**Comment by diethardsteiner** [comment]
Thanks a lot! We did a quick check and it seems to be working now. Just a note for everyone who tries to get this working: Make sure that when you define your unit test dataset, that the field column is set to the same name as the field returned by e.g. the Table input step (because since PDI without a working DB connection cannot source any metadata, all the Pentaho PDI dataset plugin can rely on is this mapping that you provide in the dataset dialog).

**Comment by Michele100** [comment]
Hi Matt,
it seems like the same issue arise when I create a Golden Data Set, as opposed to Input Data (which has been fixed).
Thanks.

**Comment by mattcasters** [comment]
The Golden part is a problem as well but it's slightly harder.  I'll look at it later this week.

**Comment by mattcasters** [comment]
Shuffled some code around, wasn't that big of a deal as I thought.

**Comment by Michele100** [comment]
Tested and it's working OK now.
Thanks Matt.
