### ISSUE TITLE
Opening an existing unit test will fail to open the transform.

### ISSUE THREAD

**Issue by usbrandon** [mattcasters/pentaho-pdi-dataset#39]
If you have multiple tests and you want to open one of the other existing tests; normally you would have the following actions

1. Click beaker icon
2. Unit Test -> Open transformation and unit test
3. From the menu observe that the path to your transform will be something like ./jobs-and-transform-folder/mytransform.ktr.
4. Choose one of the entries.
5. A message will appear stating that the transformation ./jobs-and-transformfolder/mytransform.ktr cannot be opened.  

It looks like it is not using ${ENVIRONMENT_HOME}/jobs-and-transformfolder/mytransform.ktr
Maybe it is really putting that dot  before the slash creating an invalid path (except it would work in bash given the present working directory).

**Comment by mattcasters** [comment]
Nice catch
