### ISSUE TITLE
Bug: "Guess" on field mappings does not work, even with exact match.

### ISSUE THREAD

**Issue by usbrandon** [mattcasters/pentaho-pdi-dataset#42]
In the kettle-qa/unitTests/registeredDefects/PDI-17034_db_checksum - when trying to work with say the output golden dataset and mapping the source fields to test data fields; when I click "Guess" all the mappings work except for two, which happen to be in all capital letters, but are spelled exactly the same.

I would have expected the "Guess" to be able to make exact matches appropriately as there is no real guessing involved.  Not sure why this failed.

**Comment by mattcasters** [comment]
This dialog is part of Kettle core, not of the plugin. 
I have tried raising bug reports against it without much luck.
Moving a fork of the code to a ```plugins-core``` project seems the next logical step.

**Comment by mattcasters** [comment]
TODO: move useful cross plugin code to a new plugins-core repository.
