### ISSUE TITLE
Bug: Test run by Execute Unit step must fail if test database is unavailable.

### ISSUE THREAD

**Issue by usbrandon** [mattcasters/pentaho-pdi-dataset#44]
Reference
kettle-qa/unitTests/registeredDefects/PDI-17034_db_checksum/run_unit_tests.ktr

The test set data exists in the MariaDB docker container.  I forgot to start the container.

Fruitlessly I tried the Execute Unit tests step and every time it ran and reported no errors at all, but certainly no test success.

I wish the underlying transformation would have failed and raised an error that could be caught at the level of the "Execute Unit Test" step.

**Comment by mattcasters** [comment]
I can't reproduce this.  The "Execute Unit Tests" step outputs the error message in the "comment" field and flags it as an error.
