### ISSUE TITLE
Enhancement: Execute Unit Step - Label Step Inputs and Output Fields.

### ISSUE THREAD

**Issue by usbrandon** [mattcasters/pentaho-pdi-dataset#45]
Looking at the UI, it should have been obvious which fields were being used for Input for the step and which fields would become Output fields.  

Please consider adding a label and separating horizontal line or boxing the fields that constitute inputs and outputs.

Step Input Fields:
Test Name
Type of tests to run   ( can this accept incoming field values?)

"Step Output Fields"
-------------------------------------
Transfield Name
etc.

**Comment by mattcasters** [comment]
I added "output" to the labels of the output fields.
