### ISSUE TITLE
Bug: Preview Rows: Conversion error: null on input fields after the Execute Unit Step

### ISSUE THREAD

**Issue by usbrandon** [mattcasters/pentaho-pdi-dataset#46]
Any input rows flowing into the Execute Unit Test Step come out on the other side with the "Conversion error: null" message when looking at the "Preview rows" tab.
[https://pasteboard.co/HXPwTVZ.png](https://pasteboard.co/HXPwTVZ.png)

[What happens.](https://imagebin.ca/v/4UXfzj7lXcf5)

**Comment by hansva** [comment]
In addition to this bug, fields used before the "Execute Unit Tests" are available in the preview tab but also give conversion errors, They are not in the actual result of the step so not sure if this is a bug that has to do with the plugin...
![image](https://user-images.githubusercontent.com/1140235/51681695-b7046080-1fe5-11e9-9673-b206d6199732.png)

**Comment by mattcasters** [comment]
Seems to have been fixed: 
![image](https://user-images.githubusercontent.com/1724620/59850134-cbb50c80-9369-11e9-910c-35057bf37320.png)
