### ISSUE TITLE
Bug: Using CSV dataset and "Sort Order" causes error

### ISSUE THREAD

**Issue by hansva** [mattcasters/pentaho-pdi-dataset#47]
1. create CSV data set
2. add golden dataset to a step
3. do not clear sort order

following error:
![image](https://user-images.githubusercontent.com/1140235/51680014-d9e04600-1fe0-11e9-8940-3fa0511913b7.png)

**Comment by mattcasters** [comment]
Confirmed

**Comment by hansva** [comment]
Confirmed fix
