### ISSUE TITLE
Output for golden output complains about no incoming rows when it has a row.

### ISSUE THREAD

**Issue by usbrandon** [mattcasters/pentaho-pdi-dataset#48]
When you run the test against the golden output; the logs report having the row from the golden output but not receiving a row from the stream.  The stream is delivering a row.

using v3.4.3

Reproduction:

1. Pull latest - kettle-qa
2. Open:
3. unitTests/registeredDefects/PDI-17652_wrapped_up_Internal.Entry.Current.Directory/Current_Position_Error/RUN_JOB_FROM_HERE/content/start_here.ktr
4. Load unit test PDI-17652-wrapped_up_Internal.Entry.Current.Directory Test

![screenshot from 2019-01-28 12-52-11](https://user-images.githubusercontent.com/1233654/51859736-7cf4d080-22fd-11e9-94e6-d52fc42a671c.png)

**Comment by mattcasters** [comment]
I'm getting a different complaint in the last version (3.4.4):

```2019/06/20 13:30:02 - start_test - Output - PDI-17652_Internal.Entry.Current.Directory-Output : Validation againt golden data failed for row number 1: step value [N] does not correspond to data set value [Y]
2019/06/20 13:30:02 - start_test - Output - PDI-17652_Internal.Entry.Current.Directory-Output : Validation againt golden data failed for row number 1: step value [null] does not correspond to data set value [OTHER_PROJECT/content]
```

I don't know if that's good or bad :-)  
In fact, I don't even know what this transformation is testing at all!
