### ISSUE TITLE
Create a dataset: Date formatting mask required

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/pentaho-pdi-dataset#49]
Currently there is no way to specify a date formatting mask in the **Create a dataset** window. Please add one.
![screenshot from 2019-02-09 17-37-04](https://user-images.githubusercontent.com/1726057/52524138-a0bafd80-2c91-11e9-8e1c-92460cc08d3d.png)

**Comment by mattcasters** [comment]
Are you asking for the ability to provide your own CSV files for test data sets with your own format, instead of using the Kettle tools for creating CSV files?
If so, what other features might be required?

**Comment by diethardsteiner** [comment]
Yes, we‘d usually prepare the CSV files externally. I was here actually only after a way to define the format (especially date). So all that would have to be added to the existing dialog is an extra column for specifying the format for each field.

**Comment by mattcasters** [comment]
You seem to allude to other options as well?

**Comment by diethardsteiner** [comment]
No not really. All I primarily would like to have is a format column in the table just below *The data set fields and their column name in the table:*.
