### ISSUE TITLE
After Disabling Unit Tests, running the transformation yields error

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/pentaho-pdi-dataset#5]
pdi-6.1, latest release of pentaho-pdi-dataset

Error message:

2016/11/22 18:07:10 - Spoon - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : sample: preparing transformation execution failed
2016/11/22 18:07:10 - Spoon - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2016/11/22 18:07:10 - Spoon - Unit test 'null' was not found or could not be loaded
2016/11/22 18:07:10 - Spoon - 
2016/11/22 18:07:10 - Spoon - 	at org.pentaho.di.dataset.spoon.xtpoint.ChangeTransMetaPriorToExecutionExtensionPoint.callExtensionPoint(ChangeTransMetaPriorToExecutionExtensionPoint.java:77)
2016/11/22 18:07:10 - Spoon - 	at org.pentaho.di.core.extension.ExtensionPointHandler.callExtensionPoint(ExtensionPointHandler.java:46)
2016/11/22 18:07:10 - Spoon - 	at org.pentaho.di.trans.Trans.prepareExecution(Trans.java:633)
2016/11/22 18:07:10 - Spoon - 	at org.pentaho.di.ui.spoon.trans.TransGraph$29.run(TransGraph.java:4035)
2016/11/22 18:07:10 - Spoon - 	at java.lang.Thread.run(Thread.java:745)

**Comment by mattcasters** [comment]
Should be fixed in [commit](https://github.com/mattcasters/pentaho-pdi-dataset/commit/06e65c2a2d2345db5bfeb5a358e97c535d9315c8)

**Comment by usbrandon** [comment]
This error appears again in 3.4.1.  If you disable a unit test after running the unit test; it will not be disabled and you will get null pointers for trying to preview the inputs or output rows of whatever you are testing.
