### ISSUE TITLE
Write data from step to dataset: Not working any more

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/pentaho-pdi-dataset#7]
Steps to reproduce

1. Create a new Unit test
2. Create a new dataset
3. Assign Dataset as Golden Dataset to a specific step
4. Choose Unit test > Write data from step to dataset

Based on the log it seems like PDI is just running the unit test.

**Comment by mattcasters** [comment]
Sorry, that's not how it works.

1. Have any transformation, unit test as well
2. Click right on a step "Define data set with step output", create table empty DS
3. Click right on same step "Write data from step to dataset", run and populate data set
4. Use data set

**Comment by mattcasters** [comment]
Suggestions are welcome to make this easier, more trivial.  So I'll leave this one open for a while.

**Comment by diethardsteiner** [comment]
Ok, that's fine. Thanks for letting me know. I think you can close this issue.

**Comment by codek** [comment]
Following Matts instructions I can confirm this does **not** work in PDI7.0EE or PDI7.1CE.

I'm using Postgres (in fact the pentaho one!) for my unit test data.  Just trying to save the output from a datagrid step.
<img width="710" alt="screen shot 2017-05-31 at 09 09 16" src="https://cloud.githubusercontent.com/assets/495034/26622032/df7d1312-45e0-11e7-9a59-871819ecc42d.png">

Writing the data via table output works fine :)

**Comment by codek** [comment]
Actually, I think this is specific to the data grid step. It works when i try and write from a mapreduce output step. The data grid step has always been a funny one from a metadata perspective. If this is a PDI bug let me know and i'll raise it a jira.pentaho.com

**Comment by mattcasters** [comment]
It was something stupid in the way that it checked whether or not a test was defined. That is silly of-course. It is fixed now in 2.0.0
