### ISSUE TITLE
Add dataset menu to narrow neck flask icon

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/pentaho-pdi-dataset#8]
Currently datasets (and especially dataset groups) have to be defined via the standard menu bar whereas other options are available via the narrow neck flask icon. 

Please rename **New** to **New Unit Test** and at the minimum please added **New Data set group**. This way, at least all the required steps for setting up a unit test can be achieved by selecting an option via the narrow neck flask icon.

**Comment by mattcasters** [comment]
Good idea

**Comment by mattcasters** [comment]
In 2.0.0
